name: recette_plus
description: "Une application de recettes moderne et intuitive"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.3.4
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # Google Sign In (pour fallback si nécessaire)
  google_sign_in: ^6.2.1
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
