name: recette_plus
description: "Une application Flutter pour les recettes et produits alimentaires"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # State management & utilities
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  
  # HTTP & Networking
  http: ^1.2.2
  
  # Date & Time
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
