import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "electronics",
    name: "Électronique",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 45,
  },
  {
    id: "clothing",
    name: "Vêtements",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 128,
  },
  {
    id: "home",
    name: "Maison & Jardin",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 67,
  },
  {
    id: "sports",
    name: "Sport & Loisirs",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 89,
  },
]

export const products: Product[] = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    price: 1199,
    originalPrice: 1299,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.8,
    reviews: 324,
    description: "Le dernier iPhone avec puce A17 Pro et appareil photo révolutionnaire.",
    inStock: true,
  },
  {
    id: 2,
    name: "MacBook Air M3",
    price: 1499,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.9,
    reviews: 156,
    description: "Ultrabook puissant avec la nouvelle puce M3 d'Apple.",
    inStock: true,
  },
  {
    id: 3,
    name: "Nike Air Max 270",
    price: 149,
    originalPrice: 179,
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
    rating: 4.6,
    reviews: 892,
    description: "Baskets confortables avec amorti Air Max visible.",
    inStock: true,
  },
  {
    id: 4,
    name: 'Samsung 4K Smart TV 55"',
    price: 699,
    originalPrice: 899,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.7,
    reviews: 234,
    description: "Téléviseur 4K avec HDR et interface Smart TV intuitive.",
    inStock: false,
  },
  {
    id: 5,
    name: "Canapé Scandinave 3 places",
    price: 899,
    image: "/placeholder.svg?height=300&width=300",
    category: "home",
    rating: 4.5,
    reviews: 67,
    description: "Canapé confortable au design nordique moderne.",
    inStock: true,
  },
  {
    id: 6,
    name: "Vélo Électrique Urban",
    price: 1299,
    originalPrice: 1499,
    image: "/placeholder.svg?height=300&width=300",
    category: "sports",
    rating: 4.8,
    reviews: 123,
    description: "Vélo électrique parfait pour les déplacements urbains.",
    inStock: true,
  },
  {
    id: 7,
    name: "Casque Sony WH-1000XM5",
    price: 349,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.9,
    reviews: 445,
    description: "Casque sans fil avec réduction de bruit active.",
    inStock: true,
  },
  {
    id: 8,
    name: "Robe d'été Fleurie",
    price: 79,
    originalPrice: 99,
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
    rating: 4.4,
    reviews: 156,
    description: "Robe légère et élégante pour l'été.",
    inStock: true,
  },
]
